# syntax=docker/dockerfile:1
FROM golang:1.27.0-alpine3.23@sha256:3747dcba41c8b0db3211fda4db61638b980e17ac5bb3c94460a975a9cfe19395

RUN apk add --no-cache git curl build-base \
    && go install github.com/air-verse/air@v1.67.4 \
    && go install github.com/swaggo/swag/cmd/swag@v1.16.6 \
    && addgroup -S -g 10001 app \
    && adduser -S -D -u 10001 -G app app

WORKDIR /app
COPY go.mod go.sum ./
RUN --mount=type=cache,target=/go/pkg/mod go mod download \
    && chown -R app:app /app /go

USER 10001:10001
EXPOSE 8080
CMD ["air", "-c", ".air.toml"]
