name: Build Flutter Build Image

on:
  push:
    branches:
      - main
    paths:
      - 'build/flutter-build.Dockerfile'
      - 'build/build.sh'
  pull_request:
    branches:
      - main
    paths:
      - 'build/flutter-build.Dockerfile'
      - 'build/build.sh'

jobs:
  build-and-push:
    runs-on: ${{ matrix.runner }}

    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
            platform: linux/amd64
            arch: amd64
          - runner: ubuntu-24.04-arm
            platform: linux/arm64
            arch: arm64

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/flutter-build
          tags: |
            type=ref,event=branch,suffix=-${{ matrix.arch }}
            type=ref,event=pr,suffix=-${{ matrix.arch }}
            type=sha,prefix={{branch}}-,suffix=-${{ matrix.arch }}
            type=raw,value=latest-${{ matrix.arch }},enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./build/flutter-build.Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=${{ matrix.arch }}
          cache-to: type=gha,mode=max,scope=${{ matrix.arch }}

  create-manifest:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    permissions:
      contents: read
      packages: write

    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push multi-arch manifest
        run: |
          docker buildx imagetools create -t ghcr.io/${{ github.repository_owner }}/flutter-build:latest \
            ghcr.io/${{ github.repository_owner }}/flutter-build:latest-amd64 \
            ghcr.io/${{ github.repository_owner }}/flutter-build:latest-arm64

          # Also create manifest for branch-specific tags
          docker buildx imagetools create -t ghcr.io/${{ github.repository_owner }}/flutter-build:main \
            ghcr.io/${{ github.repository_owner }}/flutter-build:main-amd64 \
            ghcr.io/${{ github.repository_owner }}/flutter-build:main-arm64
